# Investigação Social Media — Execução Canônica

Notebook de auditoria do Challenge 004. Os cálculos usam o mesmo `analysis_engine.py` do dashboard e dos relatórios.

**Plataformas:** Instagram, TikTok, YouTube, Bilibili e RedNote.

**Regra de leitura:** rankings são sempre contextualizados com amostra, magnitude, tempo e controles. Performance de patrocínio não é chamada de ROI sem custo/receita/conversão.

In [1]:
from pathlib import Path
import sys, pandas as pd, numpy as np
from IPython.display import display, Markdown

# Funciona dentro da pasta do projeto; em Colab, faça upload/clone do projeto inteiro.
root = Path.cwd()
if not (root / "analysis_engine.py").exists():
    candidates = [root.parent, root.parent.parent, Path('/content')]
    for c in candidates:
        if (c / "analysis_engine.py").exists():
            root = c; break
sys.path.insert(0, str(root))
from analysis_engine import *
DATA = root / "data" / "social_media_dataset.csv"
df = load_data(DATA)
print(f"Base carregada: {len(df):,} posts | {df.data_hora.min():%d/%m/%Y} a {df.data_hora.max():%d/%m/%Y}")

Base carregada: 52,214 posts | 29/05/2023 a 28/05/2025

## 1. Panorama cross-platform

In [2]:
display(platform_overview(df))

  plataforma  posts  ... interacoes_por_100_views posts_patrocinados_pct
0   Bilibili  10598  ...                19.904631              42.017362
1  Instagram  10423  ...                19.888955              41.916915
2    RedNote  10402  ...                19.900990              43.462796
3     TikTok  10296  ...                19.901853              43.133256
4    YouTube  10495  ...                19.900150              43.163411

[5 rows x 11 columns]

## 2. Universo de cruzamentos definido antes das conclusões

In [3]:
for bloco in cross_universe():
    display(Markdown(f"### {bloco['familia']}"))
    display(pd.DataFrame({'Cruzamento / pergunta': bloco['cruzamentos']}))

### Objetivos

                               Cruzamento / pergunta
0                                      visualizações
1                                           curtidas
2                                        comentários
3                                  compartilhamentos
4                                  interações totais
5  curtidas/comentários/compartilhamentos por 100...
6                   interações por 100 visualizações

### Conteúdo

                      Cruzamento / pergunta
0                                   formato
1                                 categoria
2                       formato × categoria
3  formato × categoria × tamanho do creator
4          formato × categoria × patrocínio
5                formato × duração relativa
6              categoria × duração relativa

### Creators

                               Cruzamento / pergunta
0                                 tamanho do creator
1                                  tamanho × formato
2                                tamanho × categoria
3                               tamanho × patrocínio
4  creator_id somente para auditoria de consistência

### Patrocínio

                               Cruzamento / pergunta
0                   patrocinado × todos os objetivos
1  patrocinado × formato/categoria/tamanho/audiên...
2         formato × categoria × tamanho × patrocínio
3    trajetória mensal do ganho/perda do patrocinado
4  resultado orgânico em um mês × participação pa...

### Audiência

             Cruzamento / pergunta
0  idade/gênero/localização/idioma
1              audiência × formato
2            audiência × categoria
3              audiência × tamanho
4           audiência × patrocínio
5  audiência × formato × categoria

### Tempo

                            Cruzamento / pergunta
0                                             mês
1                                       trimestre
2                                          semana
3                                             dia
4                                   dia da semana
5                              hora/faixa horária
6          primeiros 12 meses × segundos 12 meses
7                                  mudança de mix
8   mudança de resultado dentro do mesmo segmento
9                trajetória mensal de combinações
10                   possíveis mudanças de regime

### Criativo / proxies

                               Cruzamento / pergunta
0  duração relativa × formato/categoria/tamanho/p...
1                       hashtags × formato/categoria
2                quantidade de hashtags × resultados

### Robustez

                               Cruzamento / pergunta
0                                      top/bottom 1%
1                                      top/bottom 5%
2                                    média × mediana
3                              agregado × controlado
4  efeito de composição / possível paradoxo de Si...
5                 primeiro período × segundo período
6                             persistência mês a mês
7                                teste fora do tempo

### Cross-platform

                        Cruzamento / pergunta
0                       plataforma × objetivo
1                        plataforma × formato
2                      plataforma × categoria
3                        plataforma × tamanho
4                      plataforma × audiência
5                     plataforma × patrocínio
6                          plataforma × tempo
7  mesma combinação em plataformas diferentes

## 3. Auditoria da base e dos creator IDs

In [4]:
rows=[]
for p in sorted(df.plataforma.unique()):
    d=platform_data(df,p); a=audit_quality(d)
    rows.append({
        'plataforma':p,'posts':a['posts'],
        'variação relativa de views (%)':100*a['distribuicao_metricas']['visualizacoes']['variacao_relativa'],
        'creator IDs com múltiplos nomes (%)':a['creator_ids_multiplos_nomes_pct'],
        'creator IDs com múltiplas contagens (%)':a['creator_ids_multiplas_contagens_pct']
    })
display(pd.DataFrame(rows))

  plataforma  ...  creator IDs com múltiplas contagens (%)
0   Bilibili  ...                                72.555066
1  Instagram  ...                                71.596452
2    RedNote  ...                                71.953921
3     TikTok  ...                                71.740098
4    YouTube  ...                                72.070485

[5 rows x 5 columns]

## 4. Objetivos separados: alcance, conversa, compartilhamento, interação e eficiência

In [5]:
metricas=['visualizacoes','comentarios','compartilhamentos','interacoes_totais','taxa_engajamento']
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    display(Markdown(f"### {p}"))
    d=platform_data(df,p)
    out=[]
    for m in metricas:
        t=combination_analysis(d,['formato','categoria','porte_criador'],m,80,8,8)
        stable=t[(t.meses_validos>=10)&(t.meses_acima_do_padrao_pct>=60)] if 'meses_validos' in t else pd.DataFrame()
        r=(stable.iloc[0] if not stable.empty else t.iloc[0])
        out.append({
            'objetivo':METRICS[m], 'formato':r.formato,'categoria':r.categoria,'porte_criador':r.porte_criador,
            'posts':int(r.n),'resultado':r.mediana,'diferença_plataforma':r.diferenca_para_plataforma,
            'meses_válidos':r.get('meses_validos',np.nan),'meses_acima_padrão_%':r.get('meses_acima_do_padrao_pct',np.nan),
            'primeiros_12m':r.get('primeiros_12m',np.nan),'segundos_12m':r.get('segundos_12m',np.nan)
        })
    display(pd.DataFrame(out))

### Instagram

                              objetivo formato  ... primeiros_12m  segundos_12m
0                        Visualizações   video  ...  10120.000000  10121.500000
1                          Comentários   video  ...    206.500000    201.000000
2                    Compartilhamentos   video  ...    302.000000    304.000000
3                    Interações totais   image  ...   2009.500000   2015.000000
4  Interações a cada 100 visualizações   video  ...     19.938068     19.913164

[5 rows x 11 columns]

### TikTok

                              objetivo formato  ... primeiros_12m  segundos_12m
0                        Visualizações   video  ...  10118.500000  10108.000000
1                          Comentários   mixed  ...    203.000000    201.000000
2                    Compartilhamentos   image  ...    303.000000    300.000000
3                    Interações totais    text  ...   2018.000000   2019.000000
4  Interações a cada 100 visualizações    text  ...     20.032458     19.921066

[5 rows x 11 columns]

### YouTube

                              objetivo formato  ... primeiros_12m  segundos_12m
0                        Visualizações   video  ...   10095.00000  10107.000000
1                          Comentários   image  ...     198.50000    203.000000
2                    Compartilhamentos   mixed  ...     300.00000    302.000000
3                    Interações totais    text  ...    2014.00000   2020.000000
4  Interações a cada 100 visualizações    text  ...      19.99021     19.968492

[5 rows x 11 columns]

### Bilibili

                              objetivo formato  ... primeiros_12m segundos_12m
0                        Visualizações   video  ...       10109.0  10110.50000
1                          Comentários   video  ...         200.0    201.00000
2                    Compartilhamentos   image  ...         300.5    304.00000
3                    Interações totais   mixed  ...        2013.0   2015.50000
4  Interações a cada 100 visualizações   image  ...          20.0     19.85732

[5 rows x 11 columns]

### RedNote

                              objetivo formato  ... primeiros_12m  segundos_12m
0                        Visualizações   video  ...  10103.000000  10115.500000
1                          Comentários   video  ...    202.000000    201.500000
2                    Compartilhamentos   video  ...    295.500000    305.000000
3                    Interações totais   image  ...   2017.000000   2015.000000
4  Interações a cada 100 visualizações   image  ...     19.964358     19.950884

[5 rows x 11 columns]

## 5. Reconstrução temporal: o que mudou entre janelas equivalentes

In [6]:
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    d=platform_data(df,p)
    display(Markdown(f"### {p}"))
    period=d.groupby('periodo_12m').agg(posts=('id','size'),views=('visualizacoes','median'),interacoes=('interacoes_totais','median'),interacoes_por_100_views=('taxa_engajamento','median'),patrocinio_pct=('patrocinado',lambda s:100*s.mean()))
    display(period)
    display(Markdown('**Mudança de mix — categoria**'))
    display(mix_shift(d,'categoria'))
    display(Markdown('**Mudança de mix — formato**'))
    display(mix_shift(d,'formato'))

### Instagram

                    posts    views  ...  interacoes_por_100_views  patrocinio_pct
periodo_12m                         ...
Primeiros 12 meses   5239  10100.0  ...                 19.887787       41.935484
Segundos 12 meses    5184  10102.0  ...                 19.890846       41.898148

[2 rows x 5 columns]

**Mudança de mix — categoria**

periodo_12m  categoria  ...  mudanca_pontos_percentuais
0               beauty  ...                    1.940891
2                 tech  ...                   -0.613598
1            lifestyle  ...                   -1.327292

[3 rows x 4 columns]

**Mudança de mix — formato**

periodo_12m formato  ...  mudanca_pontos_percentuais
0             image  ...                    0.608616
2              text  ...                   -0.164351
1             mixed  ...                   -0.220804
3             video  ...                   -0.223462

[4 rows x 4 columns]

### TikTok

                    posts    views  ...  interacoes_por_100_views  patrocinio_pct
periodo_12m                         ...
Primeiros 12 meses   5035  10101.0  ...                 19.904885       43.316783
Segundos 12 meses    5261  10100.0  ...                 19.899120       42.957613

[2 rows x 5 columns]

**Mudança de mix — categoria**

periodo_12m  categoria  ...  mudanca_pontos_percentuais
0               beauty  ...                    1.036734
2                 tech  ...                   -0.014278
1            lifestyle  ...                   -1.022457

[3 rows x 4 columns]

**Mudança de mix — formato**

periodo_12m formato  ...  mudanca_pontos_percentuais
0             image  ...                    0.999485
2              text  ...                    0.395249
1             mixed  ...                    0.159001
3             video  ...                   -1.553735

[4 rows x 4 columns]

### YouTube

                    posts    views  ...  interacoes_por_100_views  patrocinio_pct
periodo_12m                         ...
Primeiros 12 meses   5242  10097.0  ...                 19.898489       42.846242
Segundos 12 meses    5253  10101.0  ...                 19.902186       43.479916

[2 rows x 5 columns]

**Mudança de mix — categoria**

periodo_12m  categoria  ...  mudanca_pontos_percentuais
0               beauty  ...                    1.059034
2                 tech  ...                    0.111308
1            lifestyle  ...                   -1.170342

[3 rows x 4 columns]

**Mudança de mix — formato**

periodo_12m formato  ...  mudanca_pontos_percentuais
0             image  ...                    1.424204
2              text  ...                   -0.059126
1             mixed  ...                   -0.230416
3             video  ...                   -1.134662

[4 rows x 4 columns]

### Bilibili

                    posts    views  ...  interacoes_por_100_views  patrocinio_pct
periodo_12m                         ...
Primeiros 12 meses   5357  10098.0  ...                 19.909945       41.758447
Segundos 12 meses    5241  10101.0  ...                 19.901088       42.282007

[2 rows x 5 columns]

**Mudança de mix — categoria**

periodo_12m  categoria  ...  mudanca_pontos_percentuais
2                 tech  ...                    0.659406
0               beauty  ...                    0.330841
1            lifestyle  ...                   -0.990247

[3 rows x 4 columns]

**Mudança de mix — formato**

periodo_12m formato  ...  mudanca_pontos_percentuais
2              text  ...                    0.411433
0             image  ...                    0.212370
1             mixed  ...                    0.102429
3             video  ...                   -0.726231

[4 rows x 4 columns]

### RedNote

                    posts    views  ...  interacoes_por_100_views  patrocinio_pct
periodo_12m                         ...
Primeiros 12 meses   5219  10101.0  ...                 19.900050       43.590726
Segundos 12 meses    5183  10101.0  ...                 19.901865       43.333976

[2 rows x 5 columns]

**Mudança de mix — categoria**

periodo_12m  categoria  ...  mudanca_pontos_percentuais
0               beauty  ...                    0.684652
1            lifestyle  ...                   -0.013919
2                 tech  ...                   -0.670734

[3 rows x 4 columns]

**Mudança de mix — formato**

periodo_12m formato  ...  mudanca_pontos_percentuais
3             video  ...                    1.070023
0             image  ...                    0.235412
2              text  ...                   -0.628301
1             mixed  ...                   -0.677133

[4 rows x 4 columns]

## 6. Patrocínio: agregado e controlado

In [7]:
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    d=platform_data(df,p)
    display(Markdown(f"### {p} — comparação geral"))
    display(sponsorship_overall(d,['visualizacoes','comentarios','compartilhamentos','interacoes_totais','taxa_engajamento'],n_boot=300))
    display(Markdown('**Exemplos controlados por formato × categoria × tamanho do creator (taxa de engajamento)**'))
    ctrl=sponsorship_controlled(d,'taxa_engajamento',['formato','categoria','porte_criador'],25,with_ci=False)
    display(pd.concat([ctrl.head(5),ctrl.tail(5)]).drop_duplicates())

### Instagram — comparação geral

             metrica  ...                       evidencia
0      visualizacoes  ...  diferença não separada de zero
1        comentarios  ...  diferença não separada de zero
2  compartilhamentos  ...  diferença não separada de zero
3  interacoes_totais  ...  diferença não separada de zero
4   taxa_engajamento  ...  diferença não separada de zero

[5 rows x 10 columns]

**Exemplos controlados por formato × categoria × tamanho do creator (taxa de engajamento)**

   formato  categoria  ... efeito_ordinal                         evidencia
0    video     beauty  ...       0.158211  comparação descritiva controlada
1    image       tech  ...       0.142452  comparação descritiva controlada
2    image  lifestyle  ...       0.070825  comparação descritiva controlada
3     text     beauty  ...      -0.013540  comparação descritiva controlada
4    mixed     beauty  ...       0.113257  comparação descritiva controlada
29   video       tech  ...       0.024138  comparação descritiva controlada
30   image  lifestyle  ...      -0.065081  comparação descritiva controlada
31    text     beauty  ...      -0.039394  comparação descritiva controlada
32   video     beauty  ...      -0.166477  comparação descritiva controlada
33   video  lifestyle  ...      -0.097620  comparação descritiva controlada

[10 rows x 12 columns]

### TikTok — comparação geral

             metrica  ...                       evidencia
0      visualizacoes  ...  diferença não separada de zero
1        comentarios  ...  diferença não separada de zero
2  compartilhamentos  ...  diferença não separada de zero
3  interacoes_totais  ...  diferença não separada de zero
4   taxa_engajamento  ...  diferença não separada de zero

[5 rows x 10 columns]

**Exemplos controlados por formato × categoria × tamanho do creator (taxa de engajamento)**

   formato  categoria  ... efeito_ordinal                         evidencia
0    image       tech  ...       0.148148  comparação descritiva controlada
1    image  lifestyle  ...       0.213816  comparação descritiva controlada
2    video       tech  ...       0.299735  comparação descritiva controlada
3    video       tech  ...       0.219780  comparação descritiva controlada
4    image       tech  ...       0.050820  comparação descritiva controlada
32    text  lifestyle  ...      -0.086712  comparação descritiva controlada
33   video     beauty  ...      -0.123958  comparação descritiva controlada
34    text  lifestyle  ...      -0.167347  comparação descritiva controlada
35   mixed       tech  ...      -0.136090  comparação descritiva controlada
36   video  lifestyle  ...      -0.281136  comparação descritiva controlada

[10 rows x 12 columns]

### YouTube — comparação geral

             metrica  ...                       evidencia
0      visualizacoes  ...  diferença não separada de zero
1        comentarios  ...  diferença não separada de zero
2  compartilhamentos  ...  diferença não separada de zero
3  interacoes_totais  ...  diferença não separada de zero
4   taxa_engajamento  ...  diferença não separada de zero

[5 rows x 10 columns]

**Exemplos controlados por formato × categoria × tamanho do creator (taxa de engajamento)**

   formato  categoria  ... efeito_ordinal                         evidencia
0    mixed     beauty  ...       0.221186  comparação descritiva controlada
1     text       tech  ...       0.046477  comparação descritiva controlada
2    video       tech  ...       0.061209  comparação descritiva controlada
3    image       tech  ...       0.050505  comparação descritiva controlada
4     text     beauty  ...       0.107505  comparação descritiva controlada
33   mixed  lifestyle  ...      -0.073005  comparação descritiva controlada
34   video     beauty  ...      -0.113333  comparação descritiva controlada
35   video     beauty  ...      -0.145749  comparação descritiva controlada
36    text       tech  ...      -0.312644  comparação descritiva controlada
37   image       tech  ...      -0.211712  comparação descritiva controlada

[10 rows x 12 columns]

### Bilibili — comparação geral

             metrica  ...                       evidencia
0      visualizacoes  ...  diferença não separada de zero
1        comentarios  ...  diferença não separada de zero
2  compartilhamentos  ...  diferença não separada de zero
3  interacoes_totais  ...  diferença não separada de zero
4   taxa_engajamento  ...  diferença não separada de zero

[5 rows x 10 columns]

**Exemplos controlados por formato × categoria × tamanho do creator (taxa de engajamento)**

   formato  categoria  ... efeito_ordinal                         evidencia
0    image  lifestyle  ...       0.151348  comparação descritiva controlada
1    video       tech  ...       0.141128  comparação descritiva controlada
2     text       tech  ...       0.029014  comparação descritiva controlada
3    mixed       tech  ...       0.002199  comparação descritiva controlada
4    image     beauty  ...       0.075887  comparação descritiva controlada
33   mixed     beauty  ...      -0.047238  comparação descritiva controlada
34    text  lifestyle  ...      -0.168453  comparação descritiva controlada
35    text     beauty  ...      -0.159211  comparação descritiva controlada
36   video     beauty  ...      -0.160088  comparação descritiva controlada
37   video       tech  ...      -0.225291  comparação descritiva controlada

[10 rows x 12 columns]

### RedNote — comparação geral

             metrica  ...                       evidencia
0      visualizacoes  ...  diferença não separada de zero
1        comentarios  ...  diferença não separada de zero
2  compartilhamentos  ...  diferença não separada de zero
3  interacoes_totais  ...  diferença não separada de zero
4   taxa_engajamento  ...  diferença não separada de zero

[5 rows x 10 columns]

**Exemplos controlados por formato × categoria × tamanho do creator (taxa de engajamento)**

   formato  categoria  ... efeito_ordinal                         evidencia
0    image  lifestyle  ...       0.316092  comparação descritiva controlada
1     text  lifestyle  ...       0.186756  comparação descritiva controlada
2    video     beauty  ...       0.116618  comparação descritiva controlada
3    video       tech  ...       0.153987  comparação descritiva controlada
4    mixed  lifestyle  ...       0.124194  comparação descritiva controlada
31   mixed       tech  ...      -0.014925  comparação descritiva controlada
32   video     beauty  ...      -0.136792  comparação descritiva controlada
33   image  lifestyle  ...      -0.079525  comparação descritiva controlada
34   video       tech  ...      -0.059259  comparação descritiva controlada
35   image       tech  ...      -0.253463  comparação descritiva controlada

[10 rows x 12 columns]

## 7. Audiência

In [8]:
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    d=platform_data(df,p)
    display(Markdown(f"### {p}"))
    rows=[]
    for dim in ['faixa_etaria_audiencia','genero_audiencia','localizacao_audiencia','idioma']:
        t=group_summary(d,dim,'taxa_engajamento',30)
        if not t.empty:
            rows.append({'dimensão':DIMENSION_LABELS[dim],'melhor':t.iloc[0][dim],'resultado_melhor':t.iloc[0].mediana,'pior':t.iloc[-1][dim],'resultado_pior':t.iloc[-1].mediana,'distância':t.iloc[0].mediana-t.iloc[-1].mediana})
    display(pd.DataFrame(rows))

### Instagram

                                dimensão      melhor  ...  resultado_pior distância
0        Idade predominante da audiência       26-35  ...       19.866247  0.033541
1       Gênero predominante da audiência  non-binary  ...       19.883450  0.013291
2  Localização predominante da audiência      Brazil  ...       19.870735  0.036536
3                                 Idioma     Spanish  ...       19.881722  0.023538

[4 rows x 6 columns]

### TikTok

                                dimensão   melhor  ...  resultado_pior distância
0        Idade predominante da audiência    26-35  ...       19.883519  0.035401
1       Gênero predominante da audiência  unknown  ...       19.886023  0.029527
2  Localização predominante da audiência   Russia  ...       19.884151  0.054588
3                                 Idioma  Spanish  ...       19.890873  0.042948

[4 rows x 6 columns]

### YouTube

                                dimensão  melhor  ...  resultado_pior distância
0        Idade predominante da audiência     50+  ...       19.898009  0.011719
1       Gênero predominante da audiência    male  ...       19.890511  0.021656
2  Localização predominante da audiência  Russia  ...       19.885607  0.031159
3                                 Idioma   Hindi  ...       19.891519  0.027381

[4 rows x 6 columns]

### Bilibili

                                dimensão      melhor  ...  resultado_pior distância
0        Idade predominante da audiência         50+  ...       19.896487  0.033053
1       Gênero predominante da audiência  non-binary  ...       19.893847  0.029377
2  Localização predominante da audiência          UK  ...       19.882841  0.065576
3                                 Idioma     Spanish  ...       19.897406  0.043748

[4 rows x 6 columns]

### RedNote

                                dimensão      melhor  ...  resultado_pior distância
0        Idade predominante da audiência       36-50  ...       19.859497  0.057062
1       Gênero predominante da audiência  non-binary  ...       19.893268  0.020995
2  Localização predominante da audiência       Japan  ...       19.865680  0.055307
3                                 Idioma     Chinese  ...       19.888687  0.033305

[4 rows x 6 columns]

## 8. Outliers — top/bottom 1% e 5%

In [9]:
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    d=platform_data(df,p)
    display(Markdown(f"### {p}"))
    for pct in [.01,.05]:
        x=outlier_profile(d,'taxa_engajamento',pct)
        display(Markdown(f"**Top/bottom {int(pct*100)}% — segmentos mais super-representados no topo**"))
        display(x.sort_values('indice_top',ascending=False).head(12))

### Instagram

**Top/bottom 1% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
12  taxa_engajamento           0.01  ...     2        1
8   taxa_engajamento           0.01  ...     7        1
22  taxa_engajamento           0.01  ...    18       19
1   taxa_engajamento           0.01  ...    15       10
24  taxa_engajamento           0.01  ...    17       10
35  taxa_engajamento           0.01  ...    13       12
38  taxa_engajamento           0.01  ...    26       21
50  taxa_engajamento           0.01  ...    18       17
28  taxa_engajamento           0.01  ...    15       10
43  taxa_engajamento           0.01  ...    31       27
41  taxa_engajamento           0.01  ...    25       23
6   taxa_engajamento           0.01  ...    24       18

[12 rows x 11 columns]

**Top/bottom 5% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
35  taxa_engajamento           0.05  ...    63       46
19  taxa_engajamento           0.05  ...    32       21
50  taxa_engajamento           0.05  ...    88       72
23  taxa_engajamento           0.05  ...    64       67
1   taxa_engajamento           0.05  ...    61       45
7   taxa_engajamento           0.05  ...    92       76
12  taxa_engajamento           0.05  ...     5        3
24  taxa_engajamento           0.05  ...    72       60
28  taxa_engajamento           0.05  ...    68       65
14  taxa_engajamento           0.05  ...   238      229
43  taxa_engajamento           0.05  ...   140      125
48  taxa_engajamento           0.05  ...    82       57

[12 rows x 11 columns]

### TikTok

**Top/bottom 1% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
12  taxa_engajamento           0.01  ...     2        3
23  taxa_engajamento           0.01  ...    15       12
50  taxa_engajamento           0.01  ...    22       11
34  taxa_engajamento           0.01  ...    15       10
29  taxa_engajamento           0.01  ...    17       13
28  taxa_engajamento           0.01  ...    18       14
10  taxa_engajamento           0.01  ...    65       50
17  taxa_engajamento           0.01  ...    38       27
37  taxa_engajamento           0.01  ...    25       31
41  taxa_engajamento           0.01  ...    25       23
2   taxa_engajamento           0.01  ...    13        8
44  taxa_engajamento           0.01  ...    30       28

[12 rows x 11 columns]

**Top/bottom 5% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
19  taxa_engajamento           0.05  ...    33       23
34  taxa_engajamento           0.05  ...    64       48
12  taxa_engajamento           0.05  ...     6        6
28  taxa_engajamento           0.05  ...    78       67
27  taxa_engajamento           0.05  ...    72       53
29  taxa_engajamento           0.05  ...    70       69
40  taxa_engajamento           0.05  ...   114      101
46  taxa_engajamento           0.05  ...    80       80
15  taxa_engajamento           0.05  ...   201      164
4   taxa_engajamento           0.05  ...   225      208
44  taxa_engajamento           0.05  ...   139      125
50  taxa_engajamento           0.05  ...    81       71

[12 rows x 11 columns]

### YouTube

**Top/bottom 1% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
8   taxa_engajamento           0.01  ...     8        7
27  taxa_engajamento           0.01  ...    19       17
30  taxa_engajamento           0.01  ...    19       14
35  taxa_engajamento           0.01  ...    14        6
12  taxa_engajamento           0.01  ...     1        1
46  taxa_engajamento           0.01  ...    19       12
1   taxa_engajamento           0.01  ...    13       14
26  taxa_engajamento           0.01  ...    16       14
34  taxa_engajamento           0.01  ...    13       12
9   taxa_engajamento           0.01  ...    32       34
43  taxa_engajamento           0.01  ...    31       20
0   taxa_engajamento           0.01  ...    25       22

[12 rows x 11 columns]

**Top/bottom 5% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
8   taxa_engajamento           0.05  ...    27       32
2   taxa_engajamento           0.05  ...    60       43
48  taxa_engajamento           0.05  ...    83       71
30  taxa_engajamento           0.05  ...    75       60
42  taxa_engajamento           0.05  ...   138      137
27  taxa_engajamento           0.05  ...    70       66
23  taxa_engajamento           0.05  ...    54       59
49  taxa_engajamento           0.05  ...    82       68
15  taxa_engajamento           0.05  ...   192      194
40  taxa_engajamento           0.05  ...   111       98
38  taxa_engajamento           0.05  ...   111      107
35  taxa_engajamento           0.05  ...    53       50

[12 rows x 11 columns]

### Bilibili

**Top/bottom 1% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
19  taxa_engajamento           0.01  ...    10        3
8   taxa_engajamento           0.01  ...     7        1
29  taxa_engajamento           0.01  ...    20       17
30  taxa_engajamento           0.01  ...    19        9
20  taxa_engajamento           0.01  ...    55       39
41  taxa_engajamento           0.01  ...    28       25
50  taxa_engajamento           0.01  ...    20       16
35  taxa_engajamento           0.01  ...    14        4
47  taxa_engajamento           0.01  ...    19       11
0   taxa_engajamento           0.01  ...    26       21
45  taxa_engajamento           0.01  ...    33       24
32  taxa_engajamento           0.01  ...    26       18

[12 rows x 11 columns]

**Top/bottom 5% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
19  taxa_engajamento           0.05  ...    40       25
11  taxa_engajamento           0.05  ...    32       19
10  taxa_engajamento           0.05  ...    37       31
20  taxa_engajamento           0.05  ...   234      209
50  taxa_engajamento           0.05  ...    85       70
38  taxa_engajamento           0.05  ...   118      109
27  taxa_engajamento           0.05  ...    72       79
41  taxa_engajamento           0.05  ...   117      113
32  taxa_engajamento           0.05  ...   117       94
16  taxa_engajamento           0.05  ...   201      189
12  taxa_engajamento           0.05  ...     5        8
45  taxa_engajamento           0.05  ...   143      124

[12 rows x 11 columns]

### RedNote

**Top/bottom 1% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
8   taxa_engajamento           0.01  ...     8        3
52  taxa_engajamento           0.01  ...    22       16
34  taxa_engajamento           0.01  ...    14       10
15  taxa_engajamento           0.01  ...    20       15
22  taxa_engajamento           0.01  ...    13       10
30  taxa_engajamento           0.01  ...    16        6
35  taxa_engajamento           0.01  ...    13        8
39  taxa_engajamento           0.01  ...    25       23
0   taxa_engajamento           0.01  ...    25       26
43  taxa_engajamento           0.01  ...    30       25
46  taxa_engajamento           0.01  ...    17       11
23  taxa_engajamento           0.01  ...    12       16

[12 rows x 11 columns]

**Top/bottom 5% — segmentos mais super-representados no topo**

             metrica  faixa_extrema  ... top_n bottom_n
12  taxa_engajamento           0.05  ...     7        3
24  taxa_engajamento           0.05  ...    82       72
22  taxa_engajamento           0.05  ...    62       50
47  taxa_engajamento           0.05  ...    87       70
11  taxa_engajamento           0.05  ...    25       21
2   taxa_engajamento           0.05  ...    55       41
9   taxa_engajamento           0.05  ...    86       76
25  taxa_engajamento           0.05  ...    75       61
50  taxa_engajamento           0.05  ...    83       71
42  taxa_engajamento           0.05  ...   148      123
19  taxa_engajamento           0.05  ...    28       21
41  taxa_engajamento           0.05  ...   114      117

[12 rows x 11 columns]

## 9. Hashtags e duração relativa

In [10]:
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    d=platform_data(df,p)
    display(Markdown(f"### {p}"))
    display(Markdown('**Duração relativa**'))
    display(group_summary(d,'duracao_relativa','taxa_engajamento',30))
    display(Markdown('**Hashtags com pelo menos 30 ocorrências**'))
    display(hashtag_analysis(d,'taxa_engajamento',30).head(20))

### Instagram

**Duração relativa**

  duracao_relativa     n  ...  diferenca_para_plataforma  diferenca_relativa_pct
0      Muito curta  2085  ...                   0.018224                0.091628
1            Curta  2084  ...                  -0.002272               -0.011424
2      Muito longa  2085  ...                  -0.003829               -0.019253
3            Longa  2084  ...                  -0.006971               -0.035051
4            Média  2085  ...                  -0.011764               -0.059147

[5 rows x 12 columns]

**Hashtags com pelo menos 30 ocorrências**

       hashtag   n      media  ...        p25        p75  diferenca_para_plataforma
0       before  30  20.033926  ...  19.840421  20.346318                   0.256923
1          lot  34  20.070134  ...  19.624415  20.456184                   0.249244
2       relate  33  20.072833  ...  19.601823  20.460637                   0.245539
3    including  32  20.054030  ...  19.711185  20.348575                   0.241512
4         same  30  20.073447  ...  19.900406  20.341768                   0.233414
5        whose  32  20.040071  ...  19.596895  20.374527                   0.225018
6      federal  31  20.027120  ...  19.716407  20.310074                   0.219047
7   understand  37  20.061584  ...  19.818397  20.349762                   0.212095
8         left  32  20.021889  ...  19.820216  20.298507                   0.206779
9         foot  32  19.996423  ...  19.681036  20.268653                   0.196120
10      market  34  20.045619  ...  19.683690  20.474606                   0.192390
11         air  34  20.004114  ...  19.656504  20.329340                   0.191855
12         buy  30  19.988894  ...  19.604994  20.208284                   0.185774
13        east  39  20.020522  ...  19.663086  20.320935                   0.182730
14      friend  33  20.008198  ...  19.642684  20.370002                   0.179174
15      memory  31  20.028052  ...  19.623556  20.355796                   0.156178
16    property  31  20.063317  ...  19.719915  20.370563                   0.156178
17         new  33  19.947769  ...  19.647859  20.248423                   0.154683
18        over  35  19.987122  ...  19.655329  20.329322                   0.152986
19      social  32  19.932620  ...  19.535261  20.328257                   0.147996

[20 rows x 7 columns]

### TikTok

**Duração relativa**

  duracao_relativa     n  ...  diferenca_para_plataforma  diferenca_relativa_pct
0      Muito longa  2059  ...                   0.009782                0.049149
1            Curta  2059  ...                   0.006841                0.034372
2            Média  2059  ...                   0.000443                0.002225
3            Longa  2059  ...                  -0.004355               -0.021885
4      Muito curta  2060  ...                  -0.012542               -0.063018

[5 rows x 12 columns]

**Hashtags com pelo menos 30 ocorrências**

      hashtag   n      media  ...        p25        p75  diferenca_para_plataforma
0      travel  32  20.097068  ...  19.806902  20.383058                   0.236667
1        sort  30  20.076014  ...  19.676304  20.460154                   0.230933
2     despite  35  20.004765  ...  19.633557  20.364847                   0.217669
3        fish  32  20.030663  ...  19.659757  20.316433                   0.206111
4       issue  30  20.014557  ...  19.654698  20.258406                   0.197402
5        safe  32  20.013573  ...  19.636334  20.330999                   0.194193
6      charge  31  20.036221  ...  19.691455  20.436001                   0.192896
7        beat  35  19.933558  ...  19.332465  20.292231                   0.184118
8   religious  31  20.016345  ...  19.612496  20.277427                   0.180278
9      recent  32  20.054366  ...  19.735095  20.382092                   0.173312
10    brother  30  20.079640  ...  19.631737  20.495715                   0.168670
11       know  33  20.046208  ...  19.793814  20.261050                   0.162808
12       word  31  19.943501  ...  19.685869  20.246196                   0.153913
13       last  30  19.934209  ...  19.558345  20.265659                   0.153386
14    already  30  19.943975  ...  19.582707  20.277954                   0.150558
15   cultural  31  19.988745  ...  19.604830  20.327090                   0.147701
16      enter  33  20.049704  ...  19.674369  20.352484                   0.145456
17       that  32  19.942930  ...  19.709862  20.231097                   0.144171
18       late  31  19.957593  ...  19.609132  20.255495                   0.143637
19      party  30  20.034192  ...  19.616542  20.451447                   0.141866

[20 rows x 7 columns]

### YouTube

**Duração relativa**

  duracao_relativa     n  ...  diferenca_para_plataforma  diferenca_relativa_pct
0            Curta  2099  ...                   0.010298                0.051748
1            Longa  2099  ...                   0.002763                0.013884
2      Muito longa  2099  ...                   0.000199                0.001000
3      Muito curta  2099  ...                   0.000000                0.000000
4            Média  2099  ...                  -0.014910               -0.074926

[5 rows x 12 columns]

**Hashtags com pelo menos 30 ocorrências**

       hashtag   n      media  ...        p25        p75  diferenca_para_plataforma
0          law  31  20.170120  ...  19.854377  20.450393                   0.363061
1       finish  30  20.031361  ...  19.597228  20.408062                   0.258307
2       common  30  19.926927  ...  19.654755  20.220606                   0.232724
3        whole  31  19.975404  ...  19.592285  20.293098                   0.224393
4         hard  30  20.097520  ...  19.709488  20.484371                   0.216449
5        sense  31  20.115086  ...  19.875876  20.432032                   0.213419
6        catch  34  20.055364  ...  19.700403  20.327361                   0.208462
7      account  31  20.010941  ...  19.760635  20.314544                   0.202790
8       former  32  20.077656  ...  19.674706  20.423989                   0.202424
9          guy  30  20.000053  ...  19.827634  20.225584                   0.201799
10       score  30  20.033159  ...  19.616044  20.421259                   0.195968
11     hundred  30  20.098922  ...  19.838767  20.429069                   0.190619
12        fire  32  20.042332  ...  19.698812  20.451741                   0.189838
13          by  32  19.992657  ...  19.845007  20.323937                   0.187404
14        west  34  19.981858  ...  19.660945  20.306593                   0.186138
15        vote  32  19.964095  ...  19.624359  20.262749                   0.184320
16         six  31  20.016781  ...  19.655496  20.327031                   0.183736
17   religious  43  20.000785  ...  19.698756  20.293547                   0.180374
18  everything  32  19.998659  ...  19.555093  20.431399                   0.179162
19  discussion  32  20.028112  ...  19.523578  20.339930                   0.177752

[20 rows x 7 columns]

### Bilibili

**Duração relativa**

  duracao_relativa     n  ...  diferenca_para_plataforma  diferenca_relativa_pct
0            Média  2120  ...                   0.014129                0.070982
1      Muito longa  2120  ...                   0.010679                0.053650
2      Muito curta  2120  ...                   0.003872                0.019454
3            Longa  2119  ...                  -0.005680               -0.028538
4            Curta  2119  ...                  -0.014694               -0.073821

[5 rows x 12 columns]

**Hashtags com pelo menos 30 ocorrências**

        hashtag   n      media  ...        p25        p75  diferenca_para_plataforma
0         stand  34  20.126909  ...  19.814988  20.434113                   0.280571
1         close  34  20.110747  ...  19.670393  20.378715                   0.276270
2         never  34  20.055517  ...  19.779782  20.321107                   0.247581
3      identify  32  20.123951  ...  19.743823  20.447425                   0.246609
4      attorney  30  20.106563  ...  19.834852  20.425456                   0.242651
5        member  30  20.147204  ...  19.824993  20.487436                   0.231352
6          push  30  20.024314  ...  19.761637  20.329479                   0.221667
7         movie  30  20.080972  ...  19.809437  20.445183                   0.221263
8   opportunity  31  20.074535  ...  19.763161  20.399792                   0.216653
9          safe  32  20.026969  ...  19.746632  20.230701                   0.212617
10           do  35  20.029067  ...  19.739475  20.328170                   0.205534
11         feel  30  20.066851  ...  19.819067  20.386898                   0.197139
12          war  35  20.006670  ...  19.760523  20.306236                   0.192293
13        would  30  19.959522  ...  19.675999  20.272882                   0.188662
14      exactly  40  20.033306  ...  19.675911  20.289250                   0.183750
15      however  30  20.002576  ...  19.702093  20.296580                   0.173524
16       center  39  20.097710  ...  19.753629  20.521211                   0.168111
17          art  32  20.027081  ...  19.657324  20.338519                   0.163629
18         wall  31  19.952111  ...  19.593030  20.246472                   0.160962
19   conference  33  20.044819  ...  19.546742  20.431811                   0.157851

[20 rows x 7 columns]

### RedNote

**Duração relativa**

  duracao_relativa     n  ...  diferenca_para_plataforma  diferenca_relativa_pct
0            Média  2080  ...                   0.012515                0.062886
1      Muito longa  2081  ...                   0.012216                0.061386
2            Longa  2080  ...                  -0.002020               -0.010151
3            Curta  2080  ...                  -0.007339               -0.036877
4      Muito curta  2081  ...                  -0.019655               -0.098762

[5 rows x 12 columns]

**Hashtags com pelo menos 30 ocorrências**

       hashtag   n      media  ...        p25        p75  diferenca_para_plataforma
0         upon  40  20.123220  ...  19.805234  20.439301                   0.283257
1       listen  34  20.103732  ...  19.797993  20.420739                   0.275793
2         stay  33  20.118115  ...  19.617367  20.552147                   0.253054
3      morning  36  20.072170  ...  19.749530  20.319758                   0.245869
4         from  35  20.071744  ...  19.709631  20.367926                   0.227342
5     security  31  20.055433  ...  19.799267  20.300017                   0.209674
6          fly  31  20.013091  ...  19.779303  20.338836                   0.208354
7   management  35  20.020202  ...  19.763314  20.326988                   0.204200
8        ready  34  20.159397  ...  19.730976  20.540023                   0.192219
9       nation  30  20.055823  ...  19.723778  20.387770                   0.191463
10      across  30  20.001224  ...  19.760146  20.317969                   0.188456
11      detail  30  20.036418  ...  19.605085  20.391441                   0.186775
12       bring  31  20.011253  ...  19.626298  20.418994                   0.186738
13    possible  31  20.060066  ...  19.740676  20.372412                   0.186390
14      should  38  20.084805  ...  19.855477  20.379770                   0.183548
15       dream  39  20.068527  ...  19.723229  20.329943                   0.181306
16         gas  35  20.071769  ...  19.671600  20.499218                   0.180206
17        with  31  20.016415  ...  19.729698  20.365356                   0.174957
18       start  35  20.053142  ...  19.775952  20.398873                   0.171008
19       quite  38  20.062891  ...  19.693744  20.385032                   0.166223

[20 rows x 7 columns]

## 10. Frequência semanal

In [11]:
rows=[]
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    d=platform_data(df,p)
    for m in ['visualizacoes','taxa_engajamento']:
        r=frequency_performance(d,m)
        rows.append({'plataforma':p,'métrica':METRICS[m],'relação volume semanal × resultado':r['correlacao_volume_resultado']})
display(pd.DataFrame(rows))
print('Leitura: valores próximos de zero indicam que o histórico não sustenta uma frequência semanal ótima por si só.')

  plataforma  ... relação volume semanal × resultado
0  Instagram  ...                          -0.122854
1  Instagram  ...                           0.030294
2     TikTok  ...                          -0.046796
3     TikTok  ...                          -0.149266
4    YouTube  ...                          -0.000493
5    YouTube  ...                           0.059879
6   Bilibili  ...                           0.026587
7   Bilibili  ...                           0.128802
8    RedNote  ...                          -0.108726
9    RedNote  ...                           0.092513

[10 rows x 3 columns]

Leitura: valores próximos de zero indicam que o histórico não sustenta uma frequência semanal ótima por si só.

## 11. Stress test fora do tempo

In [12]:
rows=[]
for p in ['Instagram','TikTok','YouTube','Bilibili','RedNote']:
    d=platform_data(df,p)
    for m in ['taxa_engajamento','visualizacoes']:
        r=temporal_predictability(d,m)
        rows.append({'plataforma':p,'métrica':METRICS[m],**r})
display(pd.DataFrame(rows))
print('Leitura: AUC perto de 0,50 significa que as características disponíveis no primeiro período não reconhecem os posts de maior performance no segundo melhor que aproximadamente o acaso.')

  plataforma  ... limiar_top_20_treino
0  Instagram  ...            20.311394
1  Instagram  ...         10186.000000
2     TikTok  ...            20.318957
3     TikTok  ...         10187.000000
4    YouTube  ...            20.306041
5    YouTube  ...         10184.000000
6   Bilibili  ...            20.316910
7   Bilibili  ...         10183.000000
8    RedNote  ...            20.319279
9    RedNote  ...         10184.000000

[10 rows x 8 columns]

Leitura: AUC perto de 0,50 significa que as características disponíveis no primeiro período não reconhecem os posts de maior performance no segundo melhor que aproximadamente o acaso.

## 12. Síntese metodológica

- Os cálculos deste notebook são os mesmos do dashboard e dos relatórios.
- As tabelas completas continuam exploráveis no Streamlit até o registro bruto.
- O relatório traduz os resultados para linguagem de negócio; este notebook preserva a camada de auditoria.
- A falta de gasto/receita/conversão impede ROI financeiro.
- Creator ID inconsistente não é usado como identidade longitudinal.
- Horário não vira prescrição sem timezone.
- Content length é interpretado relativamente, sem assumir unidade.